name: "Build JARs"
on:
  release:
    types: [created]
jobs:
  artifacts:
    name: "Build artifacts"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          architecture: 'x64'
      - name: Make gradlew executable
        run: chmod +x ${{ github.workspace }}/gradlew
        shell: bash
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build artifacts
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: ${{ github.workspace }}/build/libs/*.jar
          if-no-files-found: ignore
