name: "Build & run tests"
on:
  - push
jobs:
  test:
    name: "Build & test"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          architecture: 'x64'
      - name: Make gradlew executable
        run: chmod +x ${{ github.workspace }}/gradlew
        shell: bash
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Upload submitted tests report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests
          path: ${{ github.workspace }}/build/reports/tests/test/**
          if-no-files-found: ignore
